name: "Naver Cloud API Action"
description: "Action, to use Naver Cloud API Gateway"
author: "Cass07"

inputs:
  nc_api_base_url:
    description: "Naver Cloud API Gateway Base URL"
    required: true
  nc_api_uri:
    description: "Naver Cloud API Gateway URL"
    required: true
  method:
    description: "HTTP Method"
    required: true
  nc_access_key:
    description: "Naver Cloud API Gateway Access Key"
    required: true
  nc_secret_key:
    description: "Naver Cloud API Gateway Secret Key"
    required: true

outputs:
  response_body:
      description: "Response Body"

runs:
  using: docker
  image: "Dockerfile"

branding:
  icon: "cloud"
  color: green