name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: self test
        uses: cass07/navercloud-api@main
        with:
          nc_api_uri: '/api/v1/project'
          nc_api_base_url: 'https://vpcsourcedeploy.apigw.ntruss.com'
          method: 'GET'
          nc_access_key: ${{ secrets.NAVER_CLOUD_API_ACCESS_KEY }}
          nc_secret_key: ${{ secrets.NAVER_CLOUD_API_SECRET_KEY }}